//
// Created by drep on 2022-04-06.
//

#ifndef STIRLING_GAME_DEMO_CHAT_INTEGRATION_H
#define STIRLING_GAME_DEMO_CHAT_INTEGRATION_H

#endif //STIRLING_GAME_DEMO_CHAT_INTEGRATION_H


void * runChatServer() {

}
